### ISSUE TITLE
Gem Load Error during install

### ISSUE THREAD

**Issue by SummerStorm** [2beDigital/solidus_bootstraps_frontend#1]
I'm getting a Gem Load Error when running `rails generate solidus_bootstrap_frontend:install`.

Here's my Gemfile:
```
source 'https://rubygems.org'

gem 'solidus_bootstrap_frontend', git: 'https://github.com/2beDigital/solidus_bootstraps_frontend.git', tag: '2.1'

gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
gem 'pg', '~> 0.18'
gem 'puma', '~> 3.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'jquery-rails'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'

# Solidus and Solidus Authentication
gem 'solidus', '~> 2.0'
gem 'solidus_auth_devise'

group :development, :test do
  gem 'rspec-rails', '~> 3.5'
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
end

group :development do
  gem 'listen', '~> 3.0.5'
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

And here's the error from `rails generate`:
```
/home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'solidus_bootstrap_frontend'. (Bundler::GemRequireError)
Gem Load Error is: uninitialized constant SolidusFrontendBootstrap::Engine::Spree
Backtrace for gem load error is:
/home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/solidus_bootstraps_frontend-f7836db00754/solidus_bootstrap/frontend/lib/solidus_frontend_bootstrap/engine.rb:5:in `<class:Engine>'
/home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/solidus_bootstraps_frontend-f7836db00754/solidus_bootstrap/frontend/lib/solidus_frontend_bootstrap/engine.rb:4:in `<module:SolidusFrontendBootstrap>'
/home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/solidus_bootstraps_frontend-f7836db00754/solidus_bootstrap/frontend/lib/solidus_frontend_bootstrap/engine.rb:3:in `<top (required)>'
/home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/solidus_bootstraps_frontend-f7836db00754/solidus_bootstrap/frontend/lib/solidus_frontend_bootstrap.rb:2:in `require'
/home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/solidus_bootstraps_frontend-f7836db00754/solidus_bootstrap/frontend/lib/solidus_frontend_bootstrap.rb:2:in `<top (required)>'
/home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/solidus_bootstraps_frontend-f7836db00754/solidus_bootstrap/lib/solidus_bootstrap.rb:1:in `require'
/home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/solidus_bootstraps_frontend-f7836db00754/solidus_bootstrap/lib/solidus_bootstrap.rb:1:in `<top (required)>'
/home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/solidus_bootstraps_frontend-f7836db00754/lib/solidus_bootstrap_frontend.rb:1:in `require'
/home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/bundler/gems/solidus_bootstraps_frontend-f7836db00754/lib/solidus_bootstrap_frontend.rb:1:in `<top (required)>'
/home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `require'
/home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
/home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
/home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
/home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
/home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
/home/user/code/ruby/my-shop/config/application.rb:17:in `<top (required)>'
/home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:156:in `require'
/home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:156:in `require_application_and_environment!'
/home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:143:in `generate_or_destroy'
/home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:60:in `generate'
/home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
/home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:9:in `require'
bin/rails:9:in `<main>'
Bundler Error Backtrace:
	from /home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:90:in `block (2 levels) in require'
	from /home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
	from /home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
	from /home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
	from /home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
	from /home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
	from /home/user/code/ruby/my-shop/config/application.rb:17:in `<top (required)>'
	from /home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:156:in `require'
	from /home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:156:in `require_application_and_environment!'
	from /home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:143:in `generate_or_destroy'
	from /home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:60:in `generate'
	from /home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /home/user/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
	from bin/rails:9:in `require'
	from bin/rails:9:in `<main>'
```

Any help would be greatly appreciated.

**Comment by NoelDiazMesa** [comment]
Please, put 
```ruby
gem 'solidus_bootstrap_frontend', git: 'https://github.com/2beDigital/solidus_bootstraps_frontend.git', branch: 'master'
```

After:

```ruby
# Solidus and Solidus Authentication
gem 'solidus', '~> 2.0'
gem 'solidus_auth_devise'
```

This should work
